// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFfAdx11-fC4OruxP3CyHn-m_tEMviUA0',
    appId: '1:305421231201:web:8572a1dd74be7f35e07620',
    messagingSenderId: '305421231201',
    projectId: 'colinas-pets',
    authDomain: 'colinas-pets.firebaseapp.com',
    databaseURL: 'https://colinas-pets-default-rtdb.firebaseio.com',
    storageBucket: 'colinas-pets.appspot.com',
    measurementId: 'G-V3M0XY7NKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt1Zl8pfb3vZgJER2vHKqkWsl8XKkyEEg',
    appId: '1:305421231201:android:7eeac8f75666f5bae07620',
    messagingSenderId: '305421231201',
    projectId: 'colinas-pets',
    databaseURL: 'https://colinas-pets-default-rtdb.firebaseio.com',
    storageBucket: 'colinas-pets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQigMJLgH8dnuw5Tmpxno_h6qqPllktJQ',
    appId: '1:305421231201:ios:0c3d74ed9fda7b7ae07620',
    messagingSenderId: '305421231201',
    projectId: 'colinas-pets',
    databaseURL: 'https://colinas-pets-default-rtdb.firebaseio.com',
    storageBucket: 'colinas-pets.appspot.com',
    iosBundleId: 'com.example.colinasPets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQigMJLgH8dnuw5Tmpxno_h6qqPllktJQ',
    appId: '1:305421231201:ios:e3c5f120ff15a1dee07620',
    messagingSenderId: '305421231201',
    projectId: 'colinas-pets',
    databaseURL: 'https://colinas-pets-default-rtdb.firebaseio.com',
    storageBucket: 'colinas-pets.appspot.com',
    iosBundleId: 'com.example.colinasPets.RunnerTests',
  );
}
